# Generated by Django 3.2.13 on 2022-06-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='User Phone Number'),
        ),
    ]
