# Generated by Django 3.2.13 on 2022-06-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_websiteuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course_fee',
            field=models.PositiveIntegerField(blank=200, default=200, verbose_name='Course Fee'),
        ),
    ]
