# Generated by Django 3.2.13 on 2022-06-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default='13:00', verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default='12:00', verbose_name='Start Time'),
        ),
    ]
