# Generated by Django 3.2.13 on 2022-06-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_course_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='course_fee',
            field=models.PositiveIntegerField(blank=True, default=200, verbose_name='Course Fee'),
        ),
    ]
