# Generated by Django 3.2.13 on 2022-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_event_course_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='maximum_capacity',
            field=models.PositiveIntegerField(blank=True, default=10, verbose_name='Maximum Capacity'),
        ),
    ]
