# Generated by Django 3.2.13 on 2022-09-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220628_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Course Name')),
                ('course_date', models.DateField(verbose_name='Course Date')),
                ('start_time', models.TimeField(default='12:00', verbose_name='Start Time')),
                ('end_time', models.TimeField(default='13:00', verbose_name='End Time')),
                ('description', models.TextField(max_length=256, verbose_name='Event Description')),
                ('course_fee', models.PositiveIntegerField(blank=True, default=200, verbose_name='Course Fee')),
                ('maximum_capacity', models.PositiveIntegerField(blank=True, default=10, verbose_name='Maximum Capacity')),
                ('attendees', models.ManyToManyField(blank=True, to='home.WebsiteUser')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
