# Generated by Django 3.2.13 on 2022-09-12 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220911_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=256, verbose_name='Course Description'),
        ),
    ]
