# Generated by Django 3.2.13 on 2022-10-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_websiteuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='email',
            field=models.EmailField(max_length=256, null=True, verbose_name='User Email'),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='first_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='last_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='websiteuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='User Phone Number'),
        ),
    ]
