# Generated by Django 3.2.13 on 2022-10-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20221010_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Design Name')),
                ('images', models.ImageField(upload_to='', verbose_name='Design Images')),
            ],
        ),
    ]
