# Generated by Django 3.2.13 on 2022-10-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.TextField(max_length=2048, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='design',
            name='notes',
            field=models.TextField(max_length=2048, null=True, verbose_name='Notes'),
        ),
    ]
