# Generated by Django 3.2.13 on 2022-10-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221010_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Design Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='design',
            name='images',
        ),
        migrations.AddField(
            model_name='design',
            name='images',
            field=models.ManyToManyField(blank=True, to='home.Image'),
        ),
    ]
