# Generated by Django 3.2.13 on 2022-10-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20221010_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='images',
            field=models.ManyToManyField(to='home.Image'),
        ),
        migrations.AlterField(
            model_name='design',
            name='notes',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Notes'),
        ),
    ]
