# Generated by Django 3.2.13 on 2022-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20221010_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='designs',
            field=models.ManyToManyField(null=True, to='home.Design'),
        ),
    ]
