# Generated by Django 3.2.13 on 2022-10-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_course_designs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='designs',
            field=models.ManyToManyField(to='home.Design'),
        ),
    ]
