# Generated by Django 3.2.13 on 2022-11-02 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_course_designs'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Wax Weight'),
        ),
    ]
