# Generated by Django 3.2.13 on 2022-11-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_design_stones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, verbose_name='Wax Weight'),
        ),
    ]
