# Generated by Django 3.2.13 on 2022-11-12 23:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_design_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('44f8fecc-ec7d-4fd9-84ad-ae35f179802c'), editable=False),
        ),
    ]
