# Generated by Django 3.2.13 on 2022-11-14 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20221113_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaxConversion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('silver', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Silver Conversion')),
                ('y10', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='10KY Conversion')),
                ('y14', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='14KY Conversion')),
                ('y18', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='18KY Conversion')),
                ('w10', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='10KW Conversion')),
                ('w14', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='14KW Conversion')),
                ('w18', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='18KW Conversion')),
                ('pt950', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='PT950 Conversion')),
            ],
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('73b719d7-c6cf-4078-8dc7-fdb07e729ecc'), editable=False),
        ),
    ]
