# Generated by Django 3.2.13 on 2022-11-14 20:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20221113_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('28cf7a81-6c64-432e-a82b-8e4a4b4fae76'), editable=False),
        ),
        migrations.CreateModel(
            name='CourseSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.TextField(max_length=256, verbose_name='Metal Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.websiteuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.design')),
            ],
        ),
    ]
