# Generated by Django 3.2.13 on 2022-11-15 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20221114_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3c1a827a-cefd-410f-be13-810acb335000'), editable=False),
        ),
    ]
