# Generated by Django 3.2.13 on 2022-11-15 02:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20221114_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='Image', max_length=256, verbose_name='Image Name'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b4f285be-fed0-4ffc-a3fb-8f965c8558d1'), editable=False),
        ),
    ]
