# Generated by Django 3.2.13 on 2022-11-15 02:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20221114_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f19a8db8-d464-4327-9e27-4ce6e57413e8'), editable=False),
        ),
    ]
