# Generated by Django 3.2.13 on 2022-11-15 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_design_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesignup',
            name='metal_type',
            field=models.CharField(choices=[('silver', 'Silver'), ('y10', '10K Yellow Gold'), ('y14', '14K Yellow Gold'), ('y18', '18K Yellow Gold'), ('w10', '10K White Gold'), ('w14', '14K White Gold'), ('w18', '18K White Gold'), ('pt950', 'Platinum')], max_length=256, verbose_name='Metal Type'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('50bdf4a5-ed4a-49c0-853a-78c535bd2e51'), editable=False),
        ),
    ]
