# Generated by Django 3.2.13 on 2022-11-15 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20221114_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waxconversion',
            name='pt950',
        ),
        migrations.RemoveField(
            model_name='waxconversion',
            name='silver',
        ),
        migrations.RemoveField(
            model_name='waxconversion',
            name='w10',
        ),
        migrations.RemoveField(
            model_name='waxconversion',
            name='w14',
        ),
        migrations.RemoveField(
            model_name='waxconversion',
            name='w18',
        ),
        migrations.RemoveField(
            model_name='waxconversion',
            name='y10',
        ),
        migrations.RemoveField(
            model_name='waxconversion',
            name='y14',
        ),
        migrations.RemoveField(
            model_name='waxconversion',
            name='y18',
        ),
        migrations.AddField(
            model_name='design',
            name='metal_types',
            field=models.ManyToManyField(to='home.WaxConversion'),
        ),
        migrations.AddField(
            model_name='waxconversion',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Conversion'),
        ),
        migrations.AlterField(
            model_name='coursesignup',
            name='account',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='home.websiteuser'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('478ff85f-f2b4-4df1-a504-6dc7894e4f6c'), editable=False),
        ),
    ]
