# Generated by Django 3.2.13 on 2022-11-27 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20221127_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='designs',
            field=models.ManyToManyField(to='home.Design'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('77b59a3f-19e4-4ff0-8f5f-28678895d253'), editable=False),
        ),
    ]
