# Generated by Django 3.2.13 on 2022-12-04 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20221127_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a832ef50-a5a8-4c14-9a3f-a12d174e2904'), editable=False),
        ),
    ]
