# Generated by Django 3.2.13 on 2022-12-04 04:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20221203_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attendees',
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b26ebd7e-9094-49ca-b9be-d78a593d73b7'), editable=False),
        ),
    ]
