# Generated by Django 3.2.13 on 2022-12-04 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20221203_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3bfc48ee-bdbe-4caf-a3a3-59ce27c1bd58'), editable=False),
        ),
    ]
