# Generated by Django 3.2.13 on 2022-12-04 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20221203_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4a01e976-ea53-436d-9ec3-45b51032e8e6'), editable=False),
        ),
        migrations.AlterField(
            model_name='design',
            name='weight',
            field=models.FloatField(blank=True, default=0, verbose_name='Wax Weight'),
        ),
    ]
