# Generated by Django 3.2.13 on 2023-01-19 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20221204_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c540c430-fc11-4679-87a3-da08258f3114'), editable=False),
        ),
    ]
