# Generated by Django 3.2.16 on 2023-07-08 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20230708_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ca240a64-80bf-49cf-9d20-b632c3cd66ad'), editable=False),
        ),
    ]
