# Generated by Django 3.2.16 on 2023-07-09 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_design_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='stones',
            field=models.FloatField(blank=True, default=0, verbose_name='Total Carat Weight'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6683ffab-dbc5-45f2-83d4-ba36c4c8e156'), editable=False),
        ),
    ]
