# Generated by Django 3.2.16 on 2023-07-10 00:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20230709_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesignup',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Checked In'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f4e1c997-6efc-428e-8ee1-5a72a343c85d'), editable=False),
        ),
    ]
