# Generated by Django 3.2.16 on 2023-07-28 20:19

import apps.home.models
import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_alter_design_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseday',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursesignup',
            name='course',
        ),
        migrations.RemoveField(
            model_name='design',
            name='stones',
        ),
        migrations.AddField(
            model_name='coursesignup',
            name='date1',
            field=models.DateField(default=apps.home.models.datetime_now, null=True, verbose_name='First Course Date'),
        ),
        migrations.AddField(
            model_name='coursesignup',
            name='date2',
            field=models.DateField(default=apps.home.models.datetime_now, null=True, verbose_name='Second Course Date'),
        ),
        migrations.AddField(
            model_name='coursesignup',
            name='purity',
            field=models.CharField(choices=[('925', 'Sterling Silver'), ('10', '10K Gold'), ('14', '14K Gold'), ('18', '18K Gold')], default=datetime.datetime.now, max_length=128, verbose_name='Purity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='course_fee',
            field=models.PositiveIntegerField(blank=True, default=200, verbose_name='Course Fee'),
        ),
        migrations.AddField(
            model_name='design',
            name='ctw',
            field=models.FloatField(default=0, verbose_name='Total Carat Weight'),
        ),
        migrations.AlterField(
            model_name='coursesignup',
            name='metal_type',
            field=models.CharField(choices=[('SV', 'Silver'), ('YG', 'Yellow Gold'), ('WG', 'White Gold')], max_length=128, verbose_name='Metal Type'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('527ec8bb-05f1-4268-8b4a-5bc95325f36e'), editable=False),
        ),
        migrations.AlterField(
            model_name='design',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Metal Weight'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseDay',
        ),
    ]
