# Generated by Django 3.2.16 on 2023-07-28 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20230728_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesignup',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.websiteuser'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('db724721-5bb6-4b9c-acf9-4791e4cb77f2'), editable=False),
        ),
    ]
