# Generated by Django 3.2.16 on 2023-07-28 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_auto_20230728_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('28882c31-43e8-4fa1-beb7-4250fc811ab2'), editable=False),
        ),
    ]
