# Generated by Django 3.2.16 on 2023-07-29 04:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20230728_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cca6a85b-c374-4e12-b8fb-2f353a38cf61'), editable=False),
        ),
    ]
