# Generated by Django 3.2.16 on 2023-07-29 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_alter_design_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='drive_url',
            field=models.URLField(default='', verbose_name='Drive URL'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2b0515cb-0246-4114-b350-af7316e6eac5'), editable=False),
        ),
    ]
