# Generated by Django 3.2.16 on 2023-07-29 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_auto_20230729_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('477455ed-dc5f-41e9-b88f-9f6d1d4ff544'), editable=False),
        ),
    ]
