# Generated by Django 3.2.16 on 2023-07-29 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_design_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesignup',
            name='metal_type',
            field=models.CharField(choices=[('YG', 'Yellow Gold'), ('WG', 'White Gold'), ('RG', 'Rose Gold'), ('SV', 'Silver')], max_length=128, verbose_name='Metal Type'),
        ),
        migrations.AlterField(
            model_name='coursesignup',
            name='purity',
            field=models.CharField(choices=[('10k', '10K Gold'), ('14k', '14K Gold'), ('18k', '18K Gold'), ('925s', 'Sterling Silver')], max_length=128, verbose_name='Purity'),
        ),
        migrations.AlterField(
            model_name='design',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('daaec446-7ab8-4dc5-a894-91066cfb58ef'), editable=False),
        ),
    ]
