# Generated by Django 3.2.16 on 2023-08-03 06:58

import apps.home.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='no_image.jpg', null=True, storage=apps.home.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Design Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='FILE_NAME', max_length=256, verbose_name='Image Name'),
        ),
    ]
